<a href="https://colab.research.google.com/github/harshsrivastava096/Python-Libraries/blob/pandas/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Here we use pd.Series()

# Basic Series Printing

In [ ]:
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64

# Series with Ranges

In [ ]:
b = pd.Series(np.arange(1,13))
b

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

#Task: Create a Series with a range of values between 200-250

In [ ]:
c = pd.Series(np.arange(200,251), name = "Listing")
c

0     200
1     201
2     202
3     203
4     204
5     205
6     206
7     207
8     208
9     209
10    210
11    211
12    212
13    213
14    214
15    215
16    216
17    217
18    218
19    219
20    220
21    221
22    222
23    223
24    224
25    225
26    226
27    227
28    228
29    229
30    230
31    231
32    232
33    233
34    234
35    235
36    236
37    237
38    238
39    239
40    240
41    241
42    242
43    243
44    244
45    245
46    246
47    247
48    248
49    249
50    250
Name: Listing, dtype: int64

# Task: Create a Series with a range of values between 340-364, name it as Price

In [ ]:
d = pd.Series(np.arange(340,365), name = "Price")
d

0     340
1     341
2     342
3     343
4     344
5     345
6     346
7     347
8     348
9     349
10    350
11    351
12    352
13    353
14    354
15    355
16    356
17    357
18    358
19    359
20    360
21    361
22    362
23    363
24    364
Name: Price, dtype: int64

In [ ]:
e = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'], name = "Pandas")
e

a    1
b    2
c    3
d    4
e    5
Name: Pandas, dtype: int64

#Task: Create a series with 5 elements and give 5 device name as  index and also  give the name of the series as devices

In [ ]:
f = pd.Series([1,2,3,4,5],index=['Keyboard','Mouse','Monitor','Printer','Scanner'], name = "Devices")
f

Keyboard    1
Mouse       2
Monitor     3
Printer     4
Scanner     5
Name: Devices, dtype: int64

In [ ]:
g = pd.Series([1,2,3,4,5,6,7],index=np.arange(100,701,100), name = "Devices")
g

100    1
200    2
300    3
400    4
500    5
600    6
700    7
Name: Devices, dtype: int64

# Series Creation with Dictionary

In [ ]:
h = pd.Series({'a':1, 'b':2,'c':3}, name = "Dict")
h

a    1
b    2
c    3
Name: Dict, dtype: int64

# Task: Create a Series with Dictionary having 5 Fruits names and keys should be car brand names

In [ ]:
I = pd.Series(data = {
    "BMW": "Apple",
    "Audi": "Banana",
    "Tesla": "Mango",
    "Toyota": "Orange",
    "Ford": "Grapes"
})
I

BMW        Apple
Audi      Banana
Tesla      Mango
Toyota    Orange
Ford      Grapes
dtype: object

In [ ]:
#If the series is created via a dictionary
#then if you change/add the index then it will show the index, however the values will be filled with null values
#Null values in pandas are known as NaN(Not a Number)

J = pd.Series({"a":1,"b":2,"c":3},index=[2.3,4.3,5.3],name="Dict")
J

2.3   NaN
4.3   NaN
5.3   NaN
Name: Dict, dtype: float64

In [ ]:
K=pd.Series(100,index=[1,2,3,4,5,6]) # creating a series with a scalar value
K

# K.dtype
#dtype-> shows the datatype of the column/Series

# K.ndim
#ndim-> gives you the dimensions of the Series

# K.size
#size-> shows the number of elements

# K.shape
#shape-> shows the shape of the Series

# ar.reshape()--> not there in pandas. Cannot convert a Series into different dimensions directly using reshape

1    100
2    100
3    100
4    100
5    100
6    100
dtype: int64

#Slicing in Pandas

In [ ]:
L=pd.Series([1,2,3,4,5,6,7,8,9])
L
L[2:6]

2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
M=pd.Series(100,index=["a","b","c","d"])
M

a    100
b    100
c    100
d    100
dtype: int64

#Task: Create a series filled with "Hi" and the number of rows should be in between the range of 54-79

---

In [ ]:
M = pd.Series('Hi',index=range(54,80), name = "Hi List")
M

54    Hi
55    Hi
56    Hi
57    Hi
58    Hi
59    Hi
60    Hi
61    Hi
62    Hi
63    Hi
64    Hi
65    Hi
66    Hi
67    Hi
68    Hi
69    Hi
70    Hi
71    Hi
72    Hi
73    Hi
74    Hi
75    Hi
76    Hi
77    Hi
78    Hi
79    Hi
Name: Hi List, dtype: object

# Task: Create a series with the range of 300-320 and
# i) Fetch the value 308 using indexing
# ii) Fetch the range of 306-318 from the original series using slicing

In [ ]:
N = pd.Series(range(300, 321))
print("Original Series:\n")
N

# 1) Fetch value 308 using indexing
N_308 = N[8]
print("Value of 308:\n")
N_308

# 2) Fetch range 306 to 318 using slicing
N_306_318 = N[6:19]
print("Range 306 to 318:\n")
N_306_318

Original Series:

Value of 308:

Range 306 to 318:

6     306
7     307
8     308
9     309
10    310
11    311
12    312
13    313
14    314
15    315
16    316
17    317
18    318
dtype: int64

In [ ]:
ar=np.array([[1,2,3],[4,5,6]])
N=pd.Series([1,2,3],[4,5,6])# value,index
N
ar

array([[1, 2, 3],
       [4, 5, 6]])

# Task: Create a series where the values will be [6,75,37,38] and the index will be [72,17,99,72] without using 'index='

In [ ]:
O = pd.Series([6, 75, 37, 38], [72, 17, 99, 72])
O

72     6
17    75
99    37
72    38
dtype: int64

# Data Frame
#(Data, Columns, Index)

In [ ]:
P=pd.DataFrame(
    [
      [1,2,3],[4,5,6]
    ],
    columns=['col1','col2','col3'],
    index=["a","b"]
)
P

   col1  col2  col3
a     1     2     3
b     4     5     6

# Task: Create a dataframe with 3 columns and 5 rows

In [ ]:
data = {
    'Name': ['A', 'B', 'C', 'D', 'E'],
    'Age': [21, 22, 23, 24, 25],
    'City': ['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Pune']
}
Q = pd.DataFrame(data)
Q

  Name  Age     City
0    A   21    Delhi
1    B   22   Mumbai
2    C   23  Chennai
3    D   24  Kolkata
4    E   25     Pune

#Custom made Dataframe

In [ ]:
R=pd.DataFrame({"col1":[1,2,3],"col2":[4,5,6]})
R

   col1  col2
0     1     4
1     2     5
2     3     6

# Task: Create a dataframe having two columns with 3 rows. First column is of fruits and second column is cars

In [ ]:
S = pd.DataFrame({
    'Fruits': ['Apple', 'Banana', 'Mango'],
    'Cars': ['BMW', 'Audi', 'Tesla']
})
S

   Fruits   Cars
0   Apple    BMW
1  Banana   Audi
2   Mango  Tesla

# Task: Create 3 columns having the range of values as (34-38,52-56,88-92)

In [ ]:
T = pd.DataFrame({
    'Col1': range(34, 39),
    'Col2': range(52, 57),
    'Col3': range(88, 93)
})
T

   Col1  Col2  Col3
0    34    52    88
1    35    53    89
2    36    54    90
3    37    55    91
4    38    56    92

#Indexing using loc and iloc

* loc -> Location based indexing/slicing
* iloc -> position based indexing/slicing
* df[1,1] -> error
* df.loc[1,'col2']
* df.loc[3,'col2']

#Task: For Data frame having the range of values as (34-38,52-56,88-92) give me the code to find 89 and 38

In [ ]:
U = pd.DataFrame({
    'Col1': range(34, 39),
    'Col2': range(52, 57),
    'Col3': range(88, 93)
})
U

   Col1  Col2  Col3
0    34    52    88
1    35    53    89
2    36    54    90
3    37    55    91
4    38    56    92

In [ ]:
U.loc[4, 'Col1']

np.int64(38)

In [ ]:
U.loc[1, 'Col3']

np.int64(89)

# Task: For Data frame having the range of values as (34-38,52-56,88-92) give me the code to find 91,35,56 where index=["a","b","c","d","e"]

In [ ]:
V = pd.DataFrame({
    'Col1': range(34, 39),
    'Col2': range(52, 57),
    'Col3': range(88, 93)
}, index=['a', 'b', 'c', 'd', 'e'])

# Finding values
val_91 = V.loc['d', 'Col3']
val_35 = V.loc['b', 'Col1']
val_56 = V.loc['e', 'Col2']

V

   Col1  Col2  Col3
a    34    52    88
b    35    53    89
c    36    54    90
d    37    55    91
e    38    56    92

In [ ]:
val_91

np.int64(91)

In [ ]:
val_35

np.int64(35)

#Task: Create a student dataset with name, age, marks as columns and give the values accordingly for 5 rowsa and find out the values of the whole dataset and also find out the values of column marks

In [ ]:
data = {
    "Name": ["Aman", "Riya", "Karan", "Sneha", "Rahul"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)

print("Full Dataset:\n")
df

# print("Values of whole dataset:\n")
# df.values

# print("\nValues of Marks column:\n")
# df["Marks"].values

Full Dataset:

    Name  Age  Marks
0   Aman   20     85
1   Riya   21     90
2  Karan   19     78
3  Sneha   22     88
4  Rahul   20     92

# Task: Take your DataFrame and Add 2 same rows. then check the value_counts of the whole dataset and then check the value counts for Marks column

In [ ]:
data = {
    "Name": ["Aman", "Riya", "Karan", "Sneha", "Rahul"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)
print("Full Dataset:\n")
df

new_rows = pd.DataFrame(
    {
    "Name":  ["Aman", "Aman"],
    "Age":   [20, 20],
    "Marks": [85, 85]
    }
)
df = pd.concat([df, new_rows])
print("Updated DataFrame:\n")
df

print("Value counts of whole dataset:\n")
df.value_counts()

print("Value counts of Marks column:\n")
df["Marks"].value_counts()

Full Dataset:

Updated DataFrame:

Value counts of whole dataset:

Value counts of Marks column:

Marks
85    3
90    1
78    1
88    1
92    1
Name: count, dtype: int64

# Task: Create a dataset with rows in this order: 'b','d','a' and index also in this given data
# df=pd.DataFrame(
#                 {"col1":np.arange(34,39),
#                  "col2":np.arange(52,57),
#                  "col3":np.arange(88,93)
#                 },
#                 index=["a","b","c","d","e"]
#)

In [ ]:
df = pd.DataFrame({
    "col1": np.arange(34,39),
    "col2": np.arange(52,57),
    "col3": np.arange(88,93)
}, index=["a","b","c","d","e"])

print("Reorder rows:\n")
df_new = df.loc[['b', 'd', 'a']].reset_index(drop=True)
df_new

Reorder rows:

   col1  col2  col3
0    35    53    89
1    37    55    91
2    34    52    88

In [ ]:
data_duplicates = {
"Student_ID":
[
"S001","S002","S003","S004","S005","S006","S007","S008","S009","S010",
"S011","S012","S013","S014","S015","S016","S017","S018","S019","S020",
"S005","S012","S021","S022","S023","S024","S025","S026","S027","S028"
],

"Name":
[
"Aman","Riya","Karan","Sneha","Rahul","Priya","Arjun","Neha","Rohan","Simran",
"Vikas","Ananya","Ritesh","Megha","Varun","Isha","Aditya","Pooja","Amit","Kriti",
"Rahul","Ananya","Dev","Nisha","Ravi","Tina","Manoj","Asha","Kunal","Divya"
],

"Course":
[
"Python","Python","Data Science","Python","Machine Learning",
"Python","Data Science","Python","Machine Learning","Python",
"Python","Data Science","Machine Learning","Python","Python",
"Data Science","Machine Learning","Python","Python","Data Science",
"Machine Learning","Data Science","Python","Machine Learning","Python",
"Data Science","Python","Machine Learning","Python","Data Science"
],

"Study_Hours":
[
10,12,8,15,9,11,14,7,13,10,
16,12,9,14,8,17,18,11,10,15,
9,12,13,16,10,14,12,9,11,13
],

"Assignment_Score":
[
75,82,68,90,70,78,85,65,80,72,
92,84,69,88,74,91,93,77,73,86,
70,84,79,90,76,87,81,69,75,82
],

"Final_Score":
[
78,85,70,92,72,80,88,66,82,75,
94,86,72,90,76,93,95,79,74,88,
72,86,83,91,79,89,84,71,77,85
]
}
dup = pd.DataFrame(data_duplicates)
# dup

# dup.info()

dup_clean = dup.drop_duplicates().reset_index(drop=True).head()
dup_clean

,Student_ID,Name,Course,Study_Hours,Assignment_Score,Final_Score
0,S001,Aman,Python,10,75,78
1,S002,Riya,Python,12,82,85
2,S003,Karan,Data Science,8,68,70
3,S004,Sneha,Python,15,90,92
4,S005,Rahul,Machine Learning,9,70,72

In [ ]:
t=pd.read_csv('https://raw.githubusercontent.com/Taj1920/Data-Analysis-Datasets/refs/heads/main/Datasets-Practice/titanic.csv')
t

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

# Task:
> Load the titanic dataset and show the shape, then top 10 rows, and then see the information

In [ ]:
t.shape

(1309, 11)

In [ ]:
t.head(10)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
5,1,"Anderson, Mr. Harry",male,48.0000,0,0,19952,26.5500,E12,S,1
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.0000,1,0,13502,77.9583,D7,S,1
7,1,"Andrews, Mr. Thomas Jr",male,39.0000,0,0,112050,0.0000,A36,S,0
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0000,2,0,11769,51.4792,C101,S,1
9,1,"Artagaveytia, Mr. Ramon",male,71.0000,0,0,PC 17609,49.5042,NaN,C,0

In [ ]:
t['pclass'].unique()

array([1, 2, 3])

In [ ]:
t['sex'].unique()

array(['female', 'male'], dtype=object)

In [ ]:
t['age'].unique()

array([29.    ,  0.9167,  2.    , 30.    , 25.    , 48.    , 63.    ,
       39.    , 53.    , 71.    , 47.    , 18.    , 24.    , 26.    ,
       80.    ,     nan, 50.    , 32.    , 36.    , 37.    , 42.    ,
       19.    , 35.    , 28.    , 45.    , 40.    , 58.    , 22.    ,
       41.    , 44.    , 59.    , 60.    , 33.    , 17.    , 11.    ,
       14.    , 49.    , 76.    , 46.    , 27.    , 64.    , 55.    ,
       70.    , 38.    , 51.    , 31.    ,  4.    , 54.    , 23.    ,
       43.    , 52.    , 16.    , 32.5   , 21.    , 15.    , 65.    ,
       28.5   , 45.5   , 56.    , 13.    , 61.    , 34.    ,  6.    ,
       57.    , 62.    , 67.    ,  1.    , 12.    , 20.    ,  0.8333,
        8.    ,  0.6667,  7.    ,  3.    , 36.5   , 18.5   ,  5.    ,
       66.    ,  9.    ,  0.75  , 70.5   , 22.5   ,  0.3333,  0.1667,
       40.5   , 10.    , 23.5   , 34.5   , 20.5   , 30.5   , 55.5   ,
       38.5   , 14.5   , 24.5   , 60.5   , 74.    ,  0.4167, 11.5   ,
       26.5   ])

In [ ]:
t['sibsp'].unique() #'sibsp'-> number of siblings and spouse travelling with the person

array([0, 1, 2, 3, 4, 5, 8])

In [ ]:
t['parch'].unique() #'parch'-> number of parents and children travelling with the person

array([0, 2, 1, 4, 3, 5, 6, 9])

In [ ]:
t['embarked'].unique() #'embarked'-> which dock they have gotten up from

array(['S', 'C', 'Q'], dtype=object)

In [ ]:
t['survived'].unique()

array([1, 0])

In [ ]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   name      1309 non-null   object
 2   sex       1309 non-null   object
 3   age       1046 non-null   float64
 4   sibsp     1309 non-null   int64
 5   parch     1309 non-null   int64
 6   ticket    1309 non-null   object
 7   fare      1308 non-null   float64
 8   cabin     295 non-null    object
 9   embarked  1307 non-null   object
 10  survived  1309 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 112.6+ KB

In [ ]:
t.isnull().sum()

pclass         0
name           0
sex            0
age          263
sibsp          0
parch          0
ticket         0
fare           1
cabin       1014
embarked       2
survived       0
dtype: int64

> Handling the missing values

In [ ]:
t['age']=t['age'].fillna(t['age'].mean())

In [ ]:
t['fare']=t['fare'].ffill() #same as above

In [ ]:
t['cabin']=t['cabin'].fillna('Unknown')

In [ ]:
t['embarked']=t['embarked'].ffill()

In [ ]:
t['embarked']=t['embarked'].bfill()

In [ ]:
t['embarked'].value_counts()

embarked
S    915
C    271
Q    123
Name: count, dtype: int64

In [ ]:
t['embarked']=t['embarked'].fillna(t['embarked'].mode()[0])

In [ ]:
t.isnull().sum()

pclass      0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
cabin       0
embarked    0
survived    0
dtype: int64

# Task:
> Fill the missing values for embarked without creating another category.

> Only 3 categories should be present (S,C,Q)

In [ ]:
t.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

# EDA(Exploratory Data Analysis)

In [ ]:
#whatever condition you pass with the square brackets those data will only be keptand the rest will be filtered out
t_age=t[t['age']>18]
t_age['age'].unique()

array([29.        , 30.        , 25.        , 48.        , 63.        ,
       39.        , 53.        , 71.        , 47.        , 24.        ,
       26.        , 80.        , 29.88113451, 50.        , 32.        ,
       36.        , 37.        , 42.        , 19.        , 35.        ,
       28.        , 45.        , 40.        , 58.        , 22.        ,
       41.        , 44.        , 59.        , 60.        , 33.        ,
       49.        , 76.        , 46.        , 27.        , 64.        ,
       55.        , 70.        , 38.        , 51.        , 31.        ,
       54.        , 23.        , 43.        , 52.        , 32.5       ,
       21.        , 65.        , 28.5       , 45.5       , 56.        ,
       61.        , 34.        , 57.        , 62.        , 67.        ,
       20.        , 36.5       , 18.5       , 66.        , 70.5       ,
       22.5       , 40.5       , 23.5       , 34.5       , 20.5       ,
       30.5       , 55.5       , 38.5       , 24.5       , 60.5       ,
       74.        , 26.5       ])

In [ ]:
t['age'].unique()

array([29.        ,  0.9167    ,  2.        , 30.        , 25.        ,
       48.        , 63.        , 39.        , 53.        , 71.        ,
       47.        , 18.        , 24.        , 26.        , 80.        ,
       29.88113451, 50.        , 32.        , 36.        , 37.        ,
       42.        , 19.        , 35.        , 28.        , 45.        ,
       40.        , 58.        , 22.        , 41.        , 44.        ,
       59.        , 60.        , 33.        , 17.        , 11.        ,
       14.        , 49.        , 76.        , 46.        , 27.        ,
       64.        , 55.        , 70.        , 38.        , 51.        ,
       31.        ,  4.        , 54.        , 23.        , 43.        ,
       52.        , 16.        , 32.5       , 21.        , 15.        ,
       65.        , 28.5       , 45.5       , 56.        , 13.        ,
       61.        , 34.        ,  6.        , 57.        , 62.        ,
       67.        ,  1.        , 12.        , 20.        ,  0.8333    ,
        8.        ,  0.6667    ,  7.        ,  3.        , 36.5       ,
       18.5       ,  5.        , 66.        ,  9.        ,  0.75      ,
       70.5       , 22.5       ,  0.3333    ,  0.1667    , 40.5       ,
       10.        , 23.5       , 34.5       , 20.5       , 30.5       ,
       55.5       , 38.5       , 14.5       , 24.5       , 60.5       ,
       74.        ,  0.4167    , 11.5       , 26.5       ])

# Task:
> Find out the people who belong to class 1.

In [ ]:
pclass=t[t['pclass']==1]
pclass['pclass'].unique()

array([1])

# Task:
> Find out the ages of the people whose fare is less than 150

In [ ]:
t[t['fare']<150]['age']

5       48.000000
6       63.000000
7       39.000000
8       53.000000
9       71.000000
          ...
1304    14.500000
1305    29.881135
1306    26.500000
1307    27.000000
1308    29.000000
Name: age, Length: 1258, dtype: float64

In [ ]:
t.loc[t['fare']<150,'age']

5       48.000000
6       63.000000
7       39.000000
8       53.000000
9       71.000000
          ...
1304    14.500000
1305    29.881135
1306    26.500000
1307    27.000000
1308    29.000000
Name: age, Length: 1258, dtype: float64

# and-> &, or-> |, not-> ~, not equal to -> !=

# Task:
> Find out the people whose fare is greater than 150 and those who are male

In [ ]:
t[(t['fare'] > 150) & (t['sex'] == 'male')]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0
10,1,"Astor, Col. John Jacob",male,47.000000,1,0,PC 17757,227.5250,C62 C64,C,0
16,1,"Baxter, Mr. Quigg Edmond",male,24.000000,0,1,PC 17558,247.5208,B58 B60,C,0
49,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.000000,0,1,PC 17755,512.3292,B51 B53 B55,C,1
106,1,"Farthing, Mr. John",male,29.881135,0,0,PC 17483,221.7792,C95,S,0
114,1,"Fortune, Mr. Charles Alexander",male,19.000000,3,2,19950,263.0000,C23 C25 C27,S,0
115,1,"Fortune, Mr. Mark",male,64.000000,1,4,19950,263.0000,C23 C25 C27,S,0
138,1,"Graham, Mr. George Edward",male,38.000000,0,1,PC 17582,153.4625,C91,S,0
173,1,"Keeping, Mr. Edwin",male,32.500000,0,0,113503,211.5000,C132,C,0
183,1,"Lesurer, Mr. Gustave J",male,35.000000,0,0,PC 17755,512.3292,B101,C,1
237,1,"Robbins, Mr. Victor",male,29.881135,0,0,PC 17757,227.5250,Unknown,C,0
249,1,"Ryerson, Master. John Borie",male,13.000000,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,1
252,1,"Ryerson, Mr. Arthur Larned",male,61.000000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C,0
285,1,"Straus, Mr. Isidor",male,67.000000,1,0,PC 17483,221.7792,C55 C57,S,0
310,1,"Wick, Mr. George Dennick",male,57.000000,1,1,36928,164.8667,Unknown,S,0
312,1,"Widener, Mr. George Dunton",male,50.000000,1,1,113503,211.5000,C80,C,0
313,1,"Widener, Mr. Harry Elkins",male,27.000000,0,2,113503,211.5000,C82,C,0

# Task:
> Find passengers who are male, traveling alone and did not survive

In [ ]:
t[(t['sex'] == 'male') & (t['sibsp'] == 0) & (t['parch'] == 0) & (t['survived'] == 0)]

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
7,1,"Andrews, Mr. Thomas Jr",male,39.000000,0,0,112050,0.0000,A36,S,0
9,1,"Artagaveytia, Mr. Ramon",male,71.000000,0,0,PC 17609,49.5042,Unknown,C,0
15,1,"Baumann, Mr. John D",male,29.881135,0,0,PC 17318,25.9250,Unknown,S,0
19,1,"Beattie, Mr. Thomson",male,36.000000,0,0,13050,75.2417,C6,C,0
25,1,"Birnbaum, Mr. Jakob",male,25.000000,0,0,13905,26.0000,Unknown,C,0
...,...,...,...,...,...,...,...,...,...,...,...
1302,3,"Yousif, Mr. Wazli",male,29.881135,0,0,2647,7.2250,Unknown,C,0
1303,3,"Yousseff, Mr. Gerious",male,29.881135,0,0,2627,14.4583,Unknown,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,Unknown,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,Unknown,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,Unknown,S,0

# Task :
> Find passengers who did NOT embark from 'S' AND have missing cabin values

In [ ]:
t[(t['embarked'] != 's') & (t['cabin'].isna())]

Empty DataFrame
Columns: [pclass, name, sex, age, sibsp, parch, ticket, fare, cabin, embarked, survived]
Index: []

# Groupby
* It is used to group data in a column in order to perform some operations
* This efficiently works when data is categorical

* Syntax: df.groupby(column_name)

In [ ]:
t.columns

Index(['pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare',
       'cabin', 'embarked', 'survived'],
      dtype='object')

In [ ]:
t.tail()

In [ ]:
t['pclass'].unique()

array([1, 2, 3])

> df.groupby(col_name).groups- it is an attribute that will give the data in the form of dictionary and the keys will be

> the group names and the values will be the index at which the category is present in the dataset

In [ ]:
t.groupby('pclass').groups

{1: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...], 2: [323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, ...], 3: [600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, ...]}

> df.groupby(col_name).get_group(category)- it is a method to display the rows where the category is present

In [ ]:
t.groupby('pclass').get_group(1)

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
318,1,"Williams-Lambert, Mr. Fletcher Fellows",male,29.881135,0,0,113510,35.0000,C128,S,0
319,1,"Wilson, Miss. Helen Alice",female,31.000000,0,0,16966,134.5000,E39 E41,C,1
320,1,"Woolner, Mr. Hugh",male,29.881135,0,0,19947,35.5000,C52,S,1
321,1,"Wright, Mr. George",male,62.000000,0,0,113807,26.5500,Unknown,S,0
322,1,"Young, Miss. Marie Grice",female,36.000000,0,0,PC 17760,135.6333,C32,C,1

# Task:
> Find out the rows having female passengers using groupby

In [ ]:
t.groupby('sex').get_group('female')

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0
6,1,"Andrews, Miss. Kornelia Theodosia",female,63.000000,1,0,13502,77.9583,D7,S,1
8,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.000000,2,0,11769,51.4792,C101,S,1
...,...,...,...,...,...,...,...,...,...,...,...
1286,3,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.000000,0,0,2688,7.2292,Unknown,C,1
1290,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.000000,1,0,363272,7.0000,Unknown,S,1
1300,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.000000,1,0,2659,14.4542,Unknown,C,1
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,Unknown,C,0
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,Unknown,C,0

> If I want only the rows of a particular column using groupby

In [ ]:
t.groupby('pclass')['fare'].get_group(1)

0      211.3375
1      151.5500
2      151.5500
3      151.5500
4      151.5500
         ...
318     35.0000
319    134.5000
320     35.5000
321     26.5500
322    135.6333
Name: fare, Length: 323, dtype: float64

# Task
> Find out the age of passenger who embarked from 'C'

In [ ]:
t.groupby('embarked')['age'].get_group('C')

9       71.000000
10      47.000000
11      18.000000
12      24.000000
16      24.000000
          ...
1303    29.881135
1304    14.500000
1305    29.881135
1306    26.500000
1307    27.000000
Name: age, Length: 271, dtype: float64

# Task:
> Find out the age,sex,sibsp,parch of passengers who embarked from 'C'

In [ ]:
t.groupby('embarked')[['age','sex','sibsp','parch']].get_group('C')

            age     sex  sibsp  parch
9     71.000000    male      0      0
10    47.000000    male      1      0
11    18.000000  female      1      0
12    24.000000  female      0      0
16    24.000000    male      0      1
...         ...     ...    ...    ...
1303  29.881135    male      0      0
1304  14.500000  female      1      0
1305  29.881135  female      1      0
1306  26.500000    male      0      0
1307  27.000000    male      0      0

[271 rows x 4 columns]

# If I want to find out a group within another group-> multiple groupby

#Task:

> Find out the rows containing the data of female passengers who embarked from "Q"

In [ ]:
t.groupby('embarked').get_group('Q').groupby('sex').get_group('female')

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
207,1,"Minahan, Miss. Daisy E",female,33.000000,1,0,19928,90.0000,C78,Q,1
208,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.000000,1,0,19928,90.0000,C78,Q,1
469,2,"Keane, Miss. Nora A",female,29.881135,0,0,226593,12.3500,E101,Q,1
562,2,"Slayter, Miss. Hilda Mary",female,30.000000,0,0,234818,12.3500,Unknown,Q,1
667,3,"Barry, Miss. Julia",female,27.000000,0,0,330844,7.8792,Unknown,Q,0
682,3,"Bourke, Miss. Mary",female,29.881135,0,2,364848,7.7500,Unknown,Q,0
684,3,"Bourke, Mrs. John (Catherine)",female,32.000000,1,1,364849,15.5000,Unknown,Q,0
686,3,"Bradley, Miss. Bridget Delia",female,22.000000,0,0,334914,7.7250,Unknown,Q,1
692,3,"Buckley, Miss. Katherine",female,18.500000,0,0,329944,7.2833,Unknown,Q,0
695,3,"Burns, Miss. Mary Delia",female,18.000000,0,0,330963,7.8792,Unknown,Q,0
702,3,"Canavan, Miss. Mary",female,21.000000,0,0,364846,7.7500,Unknown,Q,0
709,3,"Carr, Miss. Helen ""Ellen""",female,16.000000,0,0,367231,7.7500,Unknown,Q,1
710,3,"Carr, Miss. Jeannie",female,37.000000,0,0,368364,7.7500,Unknown,Q,0
725,3,"Connolly, Miss. Kate",female,22.000000,0,0,370373,7.7500,Unknown,Q,1
726,3,"Connolly, Miss. Kate",female,30.000000,0,0,330972,7.6292,Unknown,Q,0
745,3,"Daly, Miss. Margaret Marcella ""Maggie""",female,30.000000,0,0,382650,6.9500,Unknown,Q,1
771,3,"Devaney, Miss. Margaret Delia",female,19.000000,0,0,330958,7.8792,Unknown,Q,1
779,3,"Doyle, Miss. Elizabeth",female,24.000000,0,0,368702,7.7500,Unknown,Q,0
800,3,"Fleming, Miss. Honora",female,29.881135,0,0,364859,7.7500,Unknown,Q,0
818,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.000000,0,0,35851,7.7333,Unknown,Q,1
819,3,"Glynn, Miss. Mary Agatha",female,29.881135,0,0,335677,7.7500,Unknown,Q,1
841,3,"Hagardon, Miss. Kate",female,17.000000,0,0,AQ/3. 30631,7.7333,Unknown,Q,0
856,3,"Healy, Miss. Hanora ""Nora""",female,29.881135,0,0,370375,7.7500,Unknown,Q,1
859,3,"Hegarty, Miss. Hanora ""Nora""",female,18.000000,0,0,365226,6.7500,Unknown,Q,0
865,3,"Henry, Miss. Delia",female,29.881135,0,0,382649,7.7500,Unknown,Q,0
886,3,"Jermyn, Miss. Annie",female,29.881135,0,0,14313,7.7500,Unknown,Q,1
922,3,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,29.881135,0,0,9234,7.7500,Unknown,Q,1
923,3,"Kelly, Miss. Mary",female,29.881135,0,0,14312,7.7500,Unknown,Q,1
961,3,"Lennon, Miss. Mary",female,29.881135,1,0,370371,15.5000,Unknown,Q,0
984,3,"Madigan, Miss. Margaret ""Maggie""",female,29.881135,0,0,370370,7.7500,Unknown,Q,1
987,3,"Mahon, Miss. Bridget Delia",female,29.881135,0,0,330924,7.8792,Unknown,Q,0
992,3,"Mangan, Miss. Mary",female,30.500000,0,0,364850,7.7500,Unknown,Q,0
993,3,"Mannion, Miss. Margareth",female,29.881135,0,0,36866,7.7375,Unknown,Q,1
999,3,"McCarthy, Miss. Catherine ""Katie""",female,29.881135,0,0,383123,7.7500,Unknown,Q,1
1001,3,"McCoy, Miss. Agnes",female,29.881135,2,0,367226,23.2500,Unknown,Q,1
1002,3,"McCoy, Miss. Alicia",female,29.881135,2,0,367226,23.2500,Unknown,Q,1
1004,3,"McDermott, Miss. Brigdet Delia",female,29.881135,0,0,330932,7.7875,Unknown,Q,1
1006,3,"McGovern, Miss. Mary",female,29.881135,0,0,330931,7.8792,Unknown,Q,1
1007,3,"McGowan, Miss. Anna ""Annie""",female,15.000000,0,0,330923,8.0292,Unknown,Q,1
1008,3,"McGowan, Miss. Katherine",female,35.000000,0,0,9232,7.7500,Unknown,Q,0
1012,3,"McNeill, Miss. Bridget",female,29.881135,0,0,370368,7.7500,Unknown,Q,0
1023,3,"Mockler, Miss. Helen Mary ""Ellie""",female,29.881135,0,0,330980,7.8792,Unknown,Q,1
1028,3,"Moran, Miss. Bertha",female,29.881135,1,0,371110,24.1500,Unknown,Q,1
1039,3,"Mullens, Miss. Katherine ""Katie""",female,29.881135,0,0,35852,7.7333,Unknown,Q,1
1040,3,"Mulvihill, Miss. Bertha E",female,24.000000,0,0,382653,7.7500,Unknown,Q,1
1042,3,"Murphy, Miss. Katherine ""Kate""",female,29.881135,1,0,367230,15.5000,Unknown,Q,1
1043,3,"Murphy, Miss. Margaret Jane",female,29.881135,1,0,367230,15.5000,Unknown,Q,1
1044,3,"Murphy, Miss. Nora",female,29.881135,0,0,36568,15.5000,Unknown,Q,1
1054,3,"Naughton, Miss. Hannah",female,29.881135,0,0,365237,7.7500,Unknown,Q,0
1071,3,"O'Brien, Mrs. Thomas (Johanna ""Hannah"" Godfrey)",female,29.881135,1,0,370365,15.5000,Unknown,Q,1
1076,3,"O'Donoghue, Ms. Bridget",female,29.881135,0,0,364856,7.7500,Unknown,Q,0
1077,3,"O'Driscoll, Miss. Bridget",female,29.881135,0,0,14311,7.7500,Unknown,Q,1
1078,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.881135,0,0,330959,7.8792,Unknown,Q,1
1081,3,"O'Leary, Miss. Hanora ""Norah""",female,29.881135,0,0,330919,7.8292,Unknown,Q,1
1095,3,"O'Sullivan, Miss. Bridget Mary",female,29.881135,0,0,330909,7.6292,Unknown,Q,0
1124,3,"Peters, Miss. Katie",female,29.881135,0,0,330935,8.1375,Unknown,Q,0
1146,3,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,29.1250,Unknown,Q,0
1149,3,"Riordan, Miss. Johanna ""Hannah""",female,29.881135,0,0,334915,7.7208,Unknown,Q,1
1198,3,"Shine, Miss. Ellen Natalia",female,29.881135,0,0,330968,7.7792,Unknown,Q,1
1216,3,"Smyth, Miss. Julia",female,29.881135,0,0,335432,7.7333,Unknown,Q,1

# Task:
> Find out the fare of travellers whose class is 1, embarked from 'S' and are male

In [ ]:
t.groupby(['embarked','pclass','sex'])['fare'].get_group(('S',1,'male'))

1      151.5500
3      151.5500
5       26.5500
7        0.0000
14      30.0000
         ...
307     77.2875
310    164.8667
318     35.0000
320     35.5000
321     26.5500
Name: fare, Length: 108, dtype: float64

# Feature Engineering

In [ ]:
t.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [ ]:
t['age'].describe()

count    1309.000000
mean       29.881135
std        12.883199
min         0.166700
25%        22.000000
50%        29.881135
75%        35.000000
max        80.000000
Name: age, dtype: float64

Task:
> 0-18 --> Younger age

> 19-45 --> Middle age

> > 46 --> Old Age

In [ ]:
a = []
for i in t['age']:
  if 0 < i < 18 :
    a.append('Younger age')
  elif 189< i <45:
      a.append('Middle age')
  else:
      a.append('Old age')
t['age_group'] = a
t

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,age_group
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1,Old age
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1,Younger age
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0,Younger age
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0,Old age
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0,Old age
...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,Unknown,C,0,Younger age
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,Unknown,C,0,Old age
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,Unknown,C,0,Old age
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,Unknown,C,0,Old age
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,Unknown,S,0,Old age

# Task:
> Create a fare_group column having 3 categories where:

* 1) 0-200 -> Low
* 2) 201-400 -> Medium
* 3) More than 400 -> High

In [ ]:
f=[]
for i in t['fare']:
  if i<=200:
    f.append('Low')
  elif 200<i<=400:
    f.append('Medium')
  else:
    f.append('High')
t['fare_group']=f
t

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,age_group,fare_group
0,1,"Allen, Miss. Elisabeth Walton",female,29.000000,0,0,24160,211.3375,B5,S,1,Old age,Medium
1,1,"Allison, Master. Hudson Trevor",male,0.916700,1,2,113781,151.5500,C22 C26,S,1,Younger age,Low
2,1,"Allison, Miss. Helen Loraine",female,2.000000,1,2,113781,151.5500,C22 C26,S,0,Younger age,Low
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.000000,1,2,113781,151.5500,C22 C26,S,0,Old age,Low
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.000000,1,2,113781,151.5500,C22 C26,S,0,Old age,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.500000,1,0,2665,14.4542,Unknown,C,0,Younger age,Low
1305,3,"Zabour, Miss. Thamine",female,29.881135,1,0,2665,14.4542,Unknown,C,0,Old age,Low
1306,3,"Zakarian, Mr. Mapriededer",male,26.500000,0,0,2656,7.2250,Unknown,C,0,Old age,Low
1307,3,"Zakarian, Mr. Ortin",male,27.000000,0,0,2670,7.2250,Unknown,C,0,Old age,Low
1308,3,"Zimmerman, Mr. Leo",male,29.000000,0,0,315082,7.8750,Unknown,S,0,Old age,Low

In [ ]:
t['age_group'].unique()

array(['Old age', 'Younger age'], dtype=object)

In [ ]:
t['fare_group'].unique()

array(['Medium', 'Low', 'High'], dtype=object)